FILES_DIRECTORY_OF_MONTHLY = r"E:\a.bazzaz\SIEM Report Automation With Python Project\files\monthly"
FILES_DIRECTORY_OF_QUARTERLY = r"E:\a.bazzaz\SIEM Report Automation With Python Project\files\quarterly"
ARCHIVE_FILE_DIRECTORY__OF_MONTHLY_REPORT = r"E:\a.bazzaz\SIEM Report Automation With Python Project\archive\successful\monthly"
ARCHIVE_FILE_DIRECTORY__OF_QUARTERLY_REPORT = r"E:\a.bazzaz\SIEM Report Automation With Python Project\archive\successful\quarterly"
MAPPING_FILES_DIRECTORY = r"E:\a.bazzaz\SIEM Report Automation With Python Project\mappings"
LOGS_DIRECTORY = r"E:\a.bazzaz\SIEM Report Automation With Python Project\logs"
