FILES_DIRECTORY = r"E:\a.bazzaz\SIEM Report Automation With Python Project\files"
ARCHIVE_FILE_DIRECTORY__OF_MONTHLY_REPORT = r"E:\a.bazzaz\SIEM Report Automation With Python Project\archive\successful\monthly"
MAPPING_FILES_DIRECTORY = r"E:\a.bazzaz\SIEM Report Automation With Python Project\mappings"
LOGS_DIRECTORY = r"E:\a.bazzaz\SIEM Report Automation With Python Project\logs"
ARCHIVE_FILE_DIRECTORY__OF_UNSUCCESSFUL_MONTHLY_REPORT = r"E:\a.bazzaz\SIEM Report Automation With Python Project\archive\unsuccessful\monthly"
